name: "Deploy to Cloud Storage"
description: "Authenticate then upload the artifact to cloud storage"

inputs:
    environment:
        description: "Name of the environment. The file .github/variables/<environment>.env will be loaded."
        required: false
        default: ""

runs:
    using: "composite"
    steps:
        - name: Checkout project
          uses: actions/checkout@v3
          with:
              # Make sure to checkout the ref for the workflow as the latest commit on the ref
              # may have change from previous jobs.
              ref: ${{ github.ref }}

        - name: Load environment variables
          uses: apiday/load-env@v1
          with:
              environment: "${{ github.ref_name }}"

        - name: Download build artifact
          uses: actions/download-artifact@v2
          with:
              name: nextjs-build
              path: out

        - name: Authenticate with GCP
          uses: "google-github-actions/auth@v0"
          with:
              workload_identity_provider: "${{ env.WORKFLOW_IDENTITY_PROVIDER }}"
              service_account: "${{ env.SERVICE_ACCOUNT }}"

        - name: Upload static files to bucket
          uses: "google-github-actions/upload-cloud-storage@v0.10.2"
          with:
              path: "${{ github.workspace }}/out"
              destination: "${{ env.BUCKET_NAME }}"
              parent: false

        - name: Prevent caching of HTML pages
          uses: "google-github-actions/upload-cloud-storage@v0.10.2"
          with:
              path: "${{ github.workspace }}/out"
              destination: "${{ env.BUCKET_NAME }}"
              parent: false
              glob: "**/*.html"
              headers: |
                  cache-control: public, max-age=0, must-revalidate
